___

# <font color= #EF4444> **Speech Radicalization Analysis** </font>
#### <font color= #f0565e> `Deep Learning`</font>
<Strong> Sofía Maldonado, Oscar Josué Rocha & Viviana Toledo </Strong>

_12/05/2026._

___

In [2]:
import pandas as pd

The data used for this project was downloaded using _Zeeschuimer_ [1], a tool developed by Digital Methods Initiative that facilitates webscrapping social media. A series of searches were performed based on common hashtags for each topic. Only the user_@ and body of the tweets was kept. Since data was webscrapped directly from Twitter, a lot of noise is to be expected in the form of emojis, URLs, mentions and more. This notebook aims to integrate and clean data before performing classification.

## <font color= #f0565e> **ICE** </font>

In [3]:
# Load data
ice1 = pd.read_csv('../data/raw/ice/twitter_DeportThemAll.csv') 
ice2 = pd.read_csv('../data/raw/ice/twitter_MassDeportationsNow.csv')
ice3 = pd.read_csv('../data/raw/ice/twitter_ICE.csv')

df_ice = pd.concat([ice1, ice2, ice3])
df_ice

,author,body
0,and cars are parked along the street. Clothes ...,video/mp4
1,01CuriousGeorge,"""This is a \""driving school\"" in Brampton. Wh..."
2,01CuriousGeorge,https://t.co/hjSx6VXsMr
3,Victory202424,@01CuriousGeorge Shaking my head…..
4,FredKrueger27,@01CuriousGeorge If he's providing proper inst...
...,...,...
837,BluebonnetsTx8,@DAGToddBlanche But you don’t stand for people...
838,WestchesterHisp,Protesta en Yonkers contra los centros de dete...
839,IBTimesUK,Fear becomes a weapon as scammers exploit frag...
840,WhatSilence,@TheJFreakinC why is my country being used to ...
841,matixcarrizo,Mind-blown by the etymology of \'nice\'! 🤯 It ...

## <font color= #f0565e> **LGTBQIA+ phobia** </font>

In [4]:
# Load Data
lgbt1 = pd.read_csv('../data/raw/lgbt/twitter_Gender-Ideology.csv') 
lgbt2 = pd.read_csv('../data/raw/lgbt/twitter_ParentsRights.csv') 
lgbt3 = pd.read_csv('../data/raw/lgbt/twitter_WokeMindVirus.csv') 
lgbt4 = pd.read_csv('../data/raw/lgbt/twitter_NoLGBT.csv') 

df_lgbt = pd.concat([lgbt1, lgbt2, lgbt3, lgbt4])
df_lgbt

            author                                               body
0         judge148  People are drawn into gender cults for three m...
1         judge148  Gender Ideology: Is it Harmful? A Heated Debat...
2         judge148  The transgender flag\'s colors—baby blue\‚ pin...
3       jamespyles  I know that #Hollywood needs a certain number ...
4         judge148  The ideology doesn\'t like to be talked about....
..             ...                                                ...
311  Uchiha_Hirsch  @Kaylaadee ... No... Have mercy! #nolgbt #that...
312     identickle  How come all shopkeepers are offended by Gay R...
313   elizeusantos  @redbullracing Tweet? Twitter is power. #F1. J...
314   elizeusantos  @WhiteHouse #GoodmorningUSA.\n\nTHE HOLY IS HO...
315   elizeusantos  THE HOLY SON CHRIST JESUS SAVE UNITED STATES O...

[2210 rows x 2 columns]

## <font color= #f0565e> **Islamophobia** </font>

In [5]:
# Load Data
islamophobia1 = pd.read_csv('../data/raw/islamophobia/twitter_BanIslam.csv') 
islamophobia2 = pd.read_csv('../data/raw/islamophobia/twitter_IslamIsTheProblem.csv') 
islamophobia3 = pd.read_csv('../data/raw/islamophobia/twitter_StopIslam.csv') 
islamophobia4 = pd.read_csv('../data/raw/islamophobia/twitter_StopIslamInvasion.csv') 

df_islamophobia = pd.concat([islamophobia1, islamophobia2, islamophobia3, islamophobia4])
df_islamophobia

             author                                               body
0          DoIt1745       @RadioGenoa #FlushTheFilth 🚽🪠\n\n#BanIslam 🚫
1          DoIt1745                            @EpochTimes #BanIslam 🚫
2     ToddyLittman2  "While @TuckerCarlson rages against Israel, an...
3    CloudWitnesses                                                  1
4    CloudWitnesses                                                  0
..              ...                                                ...
121     Hallodri_82  @Samir_alDeen Halal verbieten.\nMoscheen schli...
122      Be2Be_Club  Si le 9/11 était fait par des islamiques radic...
123  ObliteroidScam  Allemagne, un musulman pakistanais étrangle sa...
124    FilipSimoens  Australia took the only right decision! #StopI...
125    FilipSimoens  In Belgiekistan idem...\n#StopIslamInvasion #S...

[1072 rows x 2 columns]

## <font color= #f0565e> **Asian Hate** </font>

In [6]:
# Load Data
asianhate1 = pd.read_csv('../data/raw/asianhate/twitter_BoycottChina.csv') 
asianhate2 = pd.read_csv('../data/raw/asianhate/twitter_ChinaVirus.csv') 
asianhate3 = pd.read_csv('../data/raw/asianhate/twitter_FuckChina.csv') 
asianhate4 = pd.read_csv('../data/raw/asianhate/twitter_StopChina.csv') 

df_asianhate = pd.concat([asianhate1, asianhate2, asianhate3, asianhate4])
df_asianhate

,author,body
0,Dorcas Orcas,"China, this is what you are known for:\n#anima..."
1,J-Me,@USA_China_Talk @MFA_China @USAmbChina\n@XHNew...
2,Como Juan_y_Manuela 🇪🇸,#BoycottChina
3,Como Juan_y_Manuela 🇪🇸,@PhaedraXTeddy #BoycottChina
4,Flávia,@True8bebe4 #BoycottChina\n#BoycottChineseProd...
...,...,...
357,nikonikomori,#歴史改竄 #抗日战争胜利80周年 #StopChina #DiscoverJapan
358,『北九州(いま筑豊)の外道』日本列島を強く豊かに Japan is Back 🇯🇵,#StopChina https://t.co/hIrHFtLsAD
359,nikonikomori,#中国人との共生は不可能 #StopChina #JapanNews #JICA解体 #...
360,liwen,From cancer cures to defense tech—China’s reac...
361,tenzin,Forced labor is not “competitive pricing.” It’...

### <font color= #F87171> **Sub Subtitle** </font>

# <font color= #EF4444> **Bibliography & References** </font>


https://github.com/digitalmethodsinitiative/zeeschuimer