___

# <font color= #EF4444> **Speech Radicalization Analysis** </font>
#### <font color= #f0565e> `Deep Learning`</font>
<Strong> Sofía Maldonado, Oscar Josué Rocha & Viviana Toledo </Strong>

_12/05/2026._

___

In [20]:
import pandas as pd

The data used for this project was downloaded using _Zeeschuimer_ [1], a tool developed by Digital Methods Initiative that facilitates webscrapping social media. A series of searches were performed based on common hashtags for each topic. Only the user_@ and body of the tweets was kept. Since data was webscrapped directly from Twitter, a lot of noise is to be expected in the form of emojis, URLs, mentions and more. This notebook aims to integrate and clean data before performing classification.

## <font color= #f0565e> **ICE** </font>

In [62]:
# Load data
ice1 = pd.read_csv('../data/raw/ice/twitter_DeportThemAll.csv') 
ice2 = pd.read_csv('../data/raw/ice/twitter_MassDeportationsNow.csv')
ice3 = pd.read_csv('../data/raw/ice/twitter_ICE.csv')

df_ice = pd.concat([ice1, ice2, ice3])
df_ice = df_ice.query("datalegacylang == 'en'")
df_ice

,author,body,datalegacylang
0,Victory202424,@01CuriousGeorge Shaking my head…..,en
1,FredKrueger27,@01CuriousGeorge If he's providing proper inst...,en
2,TimeHackerVicki,@01CuriousGeorge What's he doing wrong? Speaki...,en
3,YoungBobTPUK,Radical Muslim recongnizes me and throughout t...,en
4,Acts17David,@YoungBobTPUK Were this guy's parents first co...,en
...,...,...,...
606,michaelasquith,@davidaxelrod @jimmykimmel @FLOTUS45\‚ please....,en
607,BluebonnetsTx8,@DAGToddBlanche But you don’t stand for peop...,en
608,IBTimesUK,Fear becomes a weapon as scammers exploit frag...,en
609,WhatSilence,@TheJFreakinC why is my country being used to ...,en
610,matixcarrizo,Mind-blown by the etymology of \'nice\'! 🤯 It ...,en

## <font color= #f0565e> **LGTBQIA+ phobia** </font>

In [63]:
# Load Data
lgbt1 = pd.read_csv('../data/raw/lgbt/twitter_GenderIdeology.csv') 
lgbt2 = pd.read_csv('../data/raw/lgbt/twitter_ParentsRights.csv') 
lgbt3 = pd.read_csv('../data/raw/lgbt/twitter_WokeMindVirus.csv') 
lgbt4 = pd.read_csv('../data/raw/lgbt/twitter_NoLGBT.csv') 

df_lgbt = pd.concat([lgbt1, lgbt2, lgbt3, lgbt4])
df_lgbt = df_lgbt.query("datalegacylang == 'en'")
df_lgbt

,author,body,datalegacylang
0,judge148,People are drawn into gender cults for three m...,en
1,judge148,Gender Ideology: Is it Harmful? A Heated Debat...,en
2,judge148,The transgender flag\'s colors—baby blue\‚ pin...,en
3,jamespyles,I know that #Hollywood needs a certain number ...,en
4,judge148,The ideology doesn\'t like to be talked about....,en
...,...,...,...
308,Uchiha_Hirsch,@Kaylaadee ... No... Have mercy! #nolgbt #that...,en
309,identickle,How come all shopkeepers are offended by Gay R...,en
310,elizeusantos,@redbullracing Tweet? Twitter is power. #F1. J...,en
311,elizeusantos,@WhiteHouse #GoodmorningUSA.\n\nTHE HOLY IS HO...,en
312,elizeusantos,THE HOLY SON CHRIST JESUS SAVE UNITED STATES O...,en

## <font color= #f0565e> **Islamophobia** </font>

In [58]:
# Load Data
islamophobia1 = pd.read_csv('../data/raw/islamophobia/twitter_BanIslam.csv') 
islamophobia2 = pd.read_csv('../data/raw/islamophobia/twitter_IslamIsTheProblem.csv') 
islamophobia3 = pd.read_csv('../data/raw/islamophobia/twitter_StopIslam.csv') 
islamophobia4 = pd.read_csv('../data/raw/islamophobia/twitter_StopIslamInvasion.csv') 

df_islamophobia = pd.concat([islamophobia1, islamophobia2, islamophobia3, islamophobia4])
df_islamophobia = df_islamophobia.query("datalegacylang == 'en'")
df_islamophobia

,author,body,datalegacylang
0,ToddyLittman2,"""While @TuckerCarlson rages against Israel, an...",en
1,LishaBrakefield,"Yes, I've been saying this.. #BanIslam",en
2,JohnnyBgood2025,#BanIslam bring back the Crusaders now!,en
3,cryttyr,#BanIslam. They're the bad dudes.,en
4,Threat2Dmocracy,"Islam is NOT A RELIGION! It's a barbaric, terr...",en
...,...,...,...
66,UPorky,Current feeling \n#StopIslamInvasion \n#IslamI...,en
67,UPorky,More huge protests in Germany. GE children en...,en
68,ub2bad2,America will never be a Islamic State its time...,en
69,MrEMusicMan9130,"@TonySeruga Mamdani claims socialist, but is a...",en
70,FilipSimoens,Australia took the only right decision! #StopI...,en

## <font color= #f0565e> **Asian Hate** </font>

In [64]:
# Load Data
asianhate1 = pd.read_csv('../data/raw/asianhate/twitter_BoycottChina.csv') 
asianhate2 = pd.read_csv('../data/raw/asianhate/twitter_ChinaVirus.csv') 
asianhate3 = pd.read_csv('../data/raw/asianhate/twitter_FuckChina.csv') 
asianhate4 = pd.read_csv('../data/raw/asianhate/twitter_StopChina.csv') 

df_asianhate = pd.concat([asianhate1, asianhate2, asianhate3, asianhate4])
df_asianhate = df_asianhate.query("datalegacylang == 'en'")
df_asianhate

,author,body,datalegacylang
0,DorcasOrcas,"China, this is what you are known for:\n#anima...",en
5,RodneyR58127664,#BoycottChina #CatAbusersChina visa workers an...,en
9,nimernight38961,#China\n#MadeInChina\n#BoycottChina\n#ChinaTra...,en
10,fish_puddle,@Samesamaalways @nimernight38961 They are ugly...,en
11,RamirezVelhagen,#BoycottChina and its culture of cruelty and b...,en
...,...,...,...
348,ChiangKaiShek81,ISIS parroting Beijing’s narrative? Convenient...,en
349,wangleehom03,"Beijing’s trade tactics: hack the critics, hij...",en
354,wangleehom03,"While China destroys Tibetan identity, leaders...",en
360,liwan003,From cancer cures to defense tech—China’s reac...,en
361,tenzin0031,Forced labor is not “competitive pricing.” It’...,en

### <font color= #F87171> **Sub Subtitle** </font>

# <font color= #EF4444> **Bibliography & References** </font>


https://github.com/digitalmethodsinitiative/zeeschuimer