## 1. Importar librerías y archivos de datos

### Instalar e importar librerías:

**Importar librerías** necesarias:

In [43]:
# Importar librerías de Python necesarias

import pandas as pd
import nltk
import re
import sys
import re
from difflib import SequenceMatcher
import matplotlib.pyplot as plt
import seaborn as sns
import random
from scipy.stats import gaussian_kde
import numpy as np
import plotly.express as px
import time
from tqdm import tqdm
from collections import defaultdict
from datetime import datetime
import math
import operator
from IPython.display import display, clear_output
import ipywidgets as widgets

**Importar y concatenar archivos de datos** (en CSV o Excel):

In [44]:
# Load data
ice1 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/ice/twitter_DeportThemAll.csv')
ice2 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/ice/twitter_MassDeportationsNow.csv')
ice3 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/ice/twitter_ICE.csv')

df_ice = pd.concat([ice1, ice2, ice3])
df_ice = df_ice.query("datalegacylang == 'en'")
df_ice

,author,body,datalegacylang
0,Victory202424,@01CuriousGeorge Shaking my head…..,en
1,FredKrueger27,@01CuriousGeorge If he's providing proper inst...,en
2,TimeHackerVicki,@01CuriousGeorge What's he doing wrong? Speaki...,en
3,YoungBobTPUK,Radical Muslim recongnizes me and throughout t...,en
4,Acts17David,@YoungBobTPUK Were this guy's parents first co...,en
...,...,...,...
606,michaelasquith,@davidaxelrod @jimmykimmel @FLOTUS45\‚ please....,en
607,BluebonnetsTx8,@DAGToddBlanche But you don’t stand for peop...,en
608,IBTimesUK,Fear becomes a weapon as scammers exploit frag...,en
609,WhatSilence,@TheJFreakinC why is my country being used to ...,en
610,matixcarrizo,Mind-blown by the etymology of \'nice\'! 🤯 It ...,en

In [45]:
# Load Data
lgbt1 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/lgbt/twitter_GenderIdeology.csv')
lgbt2 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/lgbt/twitter_ParentsRights.csv')
lgbt3 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/lgbt/twitter_WokeMindVirus.csv')
lgbt4 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/lgbt/twitter_NoLGBT.csv')

df_lgbt = pd.concat([lgbt1, lgbt2, lgbt3, lgbt4])
df_lgbt = df_lgbt.query("datalegacylang == 'en'")
df_lgbt

,author,body,datalegacylang
0,judge148,People are drawn into gender cults for three m...,en
1,judge148,Gender Ideology: Is it Harmful? A Heated Debat...,en
2,judge148,The transgender flag\'s colors—baby blue\‚ pin...,en
3,jamespyles,I know that #Hollywood needs a certain number ...,en
4,judge148,The ideology doesn\'t like to be talked about....,en
...,...,...,...
308,Uchiha_Hirsch,@Kaylaadee ... No... Have mercy! #nolgbt #that...,en
309,identickle,How come all shopkeepers are offended by Gay R...,en
310,elizeusantos,@redbullracing Tweet? Twitter is power. #F1. J...,en
311,elizeusantos,@WhiteHouse #GoodmorningUSA.\n\nTHE HOLY IS HO...,en
312,elizeusantos,THE HOLY SON CHRIST JESUS SAVE UNITED STATES O...,en

In [46]:
# Load Data
islamophobia1 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/islamophobia/twitter_BanIslam.csv')
islamophobia2 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/islamophobia/twitter_IslamIsTheProblem.csv')
islamophobia3 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/islamophobia/twitter_StopIslam.csv')
islamophobia4 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/islamophobia/twitter_StopIslamInvasion.csv')

df_islamophobia = pd.concat([islamophobia1, islamophobia2, islamophobia3, islamophobia4])
df_islamophobia = df_islamophobia.query("datalegacylang == 'en'")
df_islamophobia

,author,body,datalegacylang
0,ToddyLittman2,"""While @TuckerCarlson rages against Israel, an...",en
1,LishaBrakefield,"Yes, I've been saying this.. #BanIslam",en
2,JohnnyBgood2025,#BanIslam bring back the Crusaders now!,en
3,cryttyr,#BanIslam. They're the bad dudes.,en
4,Threat2Dmocracy,"Islam is NOT A RELIGION! It's a barbaric, terr...",en
...,...,...,...
66,UPorky,Current feeling \n#StopIslamInvasion \n#IslamI...,en
67,UPorky,More huge protests in Germany. GE children en...,en
68,ub2bad2,America will never be a Islamic State its time...,en
69,MrEMusicMan9130,"@TonySeruga Mamdani claims socialist, but is a...",en
70,FilipSimoens,Australia took the only right decision! #StopI...,en

In [47]:
# Load Data
asianhate1 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/asianhate/twitter_BoycottChina.csv')
asianhate2 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/asianhate/twitter_ChinaVirus.csv')
asianhate3 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/asianhate/twitter_FuckChina.csv')
asianhate4 = pd.read_csv('/content/drive/MyDrive/nuevos/data/raw/asianhate/twitter_StopChina.csv')

df_asianhate = pd.concat([asianhate1, asianhate2, asianhate3, asianhate4])
df_asianhate = df_asianhate.query("datalegacylang == 'en'")
df_asianhate

,author,body,datalegacylang
0,DorcasOrcas,"China, this is what you are known for:\n#anima...",en
5,RodneyR58127664,#BoycottChina #CatAbusersChina visa workers an...,en
9,nimernight38961,#China\n#MadeInChina\n#BoycottChina\n#ChinaTra...,en
10,fish_puddle,@Samesamaalways @nimernight38961 They are ugly...,en
11,RamirezVelhagen,#BoycottChina and its culture of cruelty and b...,en
...,...,...,...
348,ChiangKaiShek81,ISIS parroting Beijing’s narrative? Convenient...,en
349,wangleehom03,"Beijing’s trade tactics: hack the critics, hij...",en
354,wangleehom03,"While China destroys Tibetan identity, leaders...",en
360,liwan003,From cancer cures to defense tech—China’s reac...,en
361,tenzin0031,Forced labor is not “competitive pricing.” It’...,en

### Previsualizar datos importados:

**Previsualizar tabla** con todos los registros importados:

In [48]:
df=df_asianhate.copy()

In [49]:
# Previsualizar dataframe con CSVs importados
display(df)
print(f"Filas/Columnas (shape) en registros importados: {df.shape}")

,author,body,datalegacylang
0,DorcasOrcas,"China, this is what you are known for:\n#anima...",en
5,RodneyR58127664,#BoycottChina #CatAbusersChina visa workers an...,en
9,nimernight38961,#China\n#MadeInChina\n#BoycottChina\n#ChinaTra...,en
10,fish_puddle,@Samesamaalways @nimernight38961 They are ugly...,en
11,RamirezVelhagen,#BoycottChina and its culture of cruelty and b...,en
...,...,...,...
348,ChiangKaiShek81,ISIS parroting Beijing’s narrative? Convenient...,en
349,wangleehom03,"Beijing’s trade tactics: hack the critics, hij...",en
354,wangleehom03,"While China destroys Tibetan identity, leaders...",en
360,liwan003,From cancer cures to defense tech—China’s reac...,en
361,tenzin0031,Forced labor is not “competitive pricing.” It’...,en

Filas/Columnas (shape) en registros importados: (632, 3)

**Exportar copia en CSV con registros importados (o concatenados):**

---

## 2. Limpieza de registros importados

In [50]:
import pandas as pd
import re


hashtags_ban = {
    "DeportThemAll", "MassDeportationsNow", "ICE", "GenderIdeology",
    "ParentsRights", "WokeMindVirus", "NoLGTB", "BanIslam",
    "IslamIsTheProblem", "StopIslam", "StopIslamInvasion",
    "BoycottChina", "ChinaVirus", "FuckChina", "StopChina"
}


hashtags_ban_lower = {h.lower() for h in hashtags_ban}



def limpiar_texto(texto):
    if pd.isna(texto):
        return texto


    texto = re.sub(r'\r\n|\r|\n', ' ', texto)


    texto = texto.replace('\\n', ' ')

    texto = re.sub(r'http\S+|www\S+', '', texto)


    texto = re.sub(r'@\w+', '', texto)


    def procesar_hashtag(match):
        palabra = match.group(1)
        if palabra.lower() in hashtags_ban_lower:
            return ''
        return palabra
    texto = re.sub(r'#(\w+)', procesar_hashtag, texto)


    texto = re.sub(r'[^\x00-\x7F]+', '', texto)


    texto = texto.lower()


    texto = re.sub(r'\s+', ' ', texto).strip()

    return texto



def limpiar_y_deduplicar(df, columna):

    df_sin_dup_antes = df.drop_duplicates(subset=[columna], keep='first').copy()

    df_sin_dup_antes['clean_text'] = df_sin_dup_antes[columna].apply(limpiar_texto)


    df_final = df_sin_dup_antes.drop_duplicates(subset=['clean_text'], keep='first').reset_index(drop=True)


    df_eliminados = df_sin_dup_antes[df_sin_dup_antes.duplicated(subset=['clean_text'], keep='first')]

    return df_final, df_eliminados

In [51]:
df_final, df_eliminados = limpiar_y_deduplicar(df, 'body')

In [52]:
df_final

,author,body,datalegacylang,clean_text
0,DorcasOrcas,"China, this is what you are known for:\n#anima...",en,"china, this is what you are known for: animalr..."
1,RodneyR58127664,#BoycottChina #CatAbusersChina visa workers an...,en,catabuserschina visa workers and their employe...
2,nimernight38961,#China\n#MadeInChina\n#BoycottChina\n#ChinaTra...,en,china madeinchina chinatravel china doesn't ha...
3,fish_puddle,@Samesamaalways @nimernight38961 They are ugly...,en,"they are ugly psychopaths, monsters!!!"
4,RamirezVelhagen,#BoycottChina and its culture of cruelty and b...,en,and its culture of cruelty and brutality
...,...,...,...,...
593,ChiangKaiShek81,ISIS parroting Beijing’s narrative? Convenient...,en,isis parroting beijings narrative? convenient....
594,wangleehom03,"Beijing’s trade tactics: hack the critics, hij...",en,"beijings trade tactics: hack the critics, hija..."
595,wangleehom03,"While China destroys Tibetan identity, leaders...",en,"while china destroys tibetan identity, leaders..."
596,liwan003,From cancer cures to defense tech—China’s reac...,en,from cancer cures to defense techchinas reach ...
597,tenzin0031,Forced labor is not “competitive pricing.” It’...,en,forced labor is not competitive pricing. its a...

In [53]:
df_final.to_csv('data/interim/asianhate_clean.csv', index=False)